name: Compile & Deploy
on:
  workflow_dispatch:
  push:
    paths:
      - 'GithubActionsDemoApp/**'
      - 'Tests/**'
      - '.github/workflows/compile_and_deploy.yml'        
    branches:
      - main      
env:
  DOTNET_VERSION: 8.0.x   
  PROJECT: GithubActionsDemoApp/GithubActionsDemoApp.csproj
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4.2.2     
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.1  
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install the dependencies    
        run: dotnet restore
      - name: Compile the app
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build
      - name: Publish the app
        run: dotnet publish ${{ env.PROJECT }} -c Release -o PublishApp --runtime win-x86
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./PublishApp
          name: build
      - name: Zip publish folder contents
        run: zip -r myapp.zip ./PublishApp
      - name: GH Release
        uses: softprops/action-gh-release@v2.2.2  
        with:
          files: ./myapp.zip
          body: "Our application"
          tag_name: ${{ github.ref_name }}

          
