name: Compile & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      
env:
  DOTNET_VERSION: 8.0.x      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4.2.2     
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.1  
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install the dependencies    
        run: dotnet restore
      - name: Compile the project
        run: dotnet build --no-restore
